### ISSUE TITLE
Getting MissingAttributeError when submitting a value in the form with trailing whitespace

### ISSUE THREAD

**Issue by jmuheim** [shioyama/mobility#97]
I have a `Page` model that `translates :title, :navigation_title, :lead, :content`.

```ruby
class Page < ApplicationRecord
  extend Mobility
  translates :title, :navigation_title, :lead, :content
end
```

I'm using the following config:

```ruby
Mobility.configure do |config|
  config.default_backend = :column
  config.accessor_method = :translates
  config.query_method    = :i18n
  config.default_options = {
    fallbacks: { de: :en }
  }
end
```

I noticed a strange behaviour: whenever I submit a value using the form with a trailing whitespace (e.g. `_x`, `_x_`, or `x_`, where whitespace is substituted with an underscore) to a translated field (e.g. `lead`) I get the following error:

```
ActiveModel::MissingAttributeError at /de/pages/1
can't write unknown attribute `lead`
```

If I submit any other value (`e.g. `x`), it works perfectly.

This only happens to translated fields, not to other fields.

Any idea what's going on? I'm happy to provide more details if needed.

Here's the app I'm currently working on: https://github.com/jmuheim/base/pull/86

**Comment by shioyama** [comment]
My guess would be that it's paper trail. What if you remove it and see if you see the same issue?

**Comment by shioyama** [comment]
Hmm I'm not sure what's going wrong. I can see the error in your code, but removing all other stuff from the model it still occurs. However I don't see it in isolated Mobility specs, so something in your projects setup or gemfile is conflicting I would suppose...

**Comment by shioyama** [comment]
Ah ok it's compatibility with the `strip_attributes` gem (should be obvious). This is not a bug but a compatibility issue.

**Comment by shioyama** [comment]
I'm probably going to have to close this since I can't really guarantee compatibility with every other gem.

**Comment by jmuheim** [comment]
Thanks a lot for finding the problem.

Do you have a more specific guess on what's the problem with `strip_attributes` gem? I will create an issue on its side then.

**Comment by shioyama** [comment]
@jmuheim can you try pointing your Gemfile to the branch in #102 ?

```ruby
gem 'mobility', github: 'shioyama/mobility', branch: 'convert_attributemethods_to_plugin'
```

This branch extracts the code overriding the `attributes` hash into a plugin which is not enabled by default. I believe this should fix the problem with `strip_attributes`.

**Comment by shioyama** [comment]
@jmuheim See above, can you please try using the branch in #102? I am going to merge that branch to fix the issue here.

**Comment by jmuheim** [comment]
I'll do soon, sorry for the delay.

**Comment by shioyama** [comment]
I've merged #102. If you use the latest on `master` now, you should not have any conflict with `strip_attributes` anymore.

This will be released shortly as a change in 0.3.

**Comment by jmuheim** [comment]
Thanks a lot for your effort! 👍

**Comment by jmuheim** [comment]
Hey there!

I tried to use the master branch, and while the problem disappeared, a spec failed.

The spec checks that each translated column offers a small icon next to the input. This icon is added in a custom SimpleForm input:

```ruby
    if object.respond_to?(:translated_attribute_names) && object.translated_attribute_names.include?(attribute_name.to_s)
      help_blocks << template.content_tag(:span, nil, class: 'fa fa-globe') + ' ' + t('simple_form.inputs.better_text.multi_language')
    end
```

It seems that in the master branch the object doesn't respond to `:translated_attribute_names` anymore. But in the source the method still exists, so I'm unsure why it doesn't work like this anymore.

Any help is highly appreciated.

**Comment by shioyama** [comment]
Hmm, I've checked and for me, using the latest (0.3.3) the model instance responds to `translated_attribute_names`.

Are you sure that your model instance really doesn't respond to `translated_attribute_names`? Maybe it's something to do with simple form.

**Comment by shioyama** [comment]
I notice the problem is (possibly) connected to paper trail. I was actually thinking of creating a small gem for using mobility with paper trail.

I'm suspecting the issue might be because the `attributes` method on the model no longer includes translated attributes in 0.3.x.

Can you try setting `attribute_methods` to `true` in your config, like this:

```ruby
Mobility.configure do |config|
  config.default_backend = :column
  config.accessor_method = :translates
  config.query_method    = :i18n
  config.default_options[:fallbacks] = { de: :en }
  config.default_options[:attribute_methods] = true
end
```

?

**Comment by shioyama** [comment]
btw, this is a wrap-up of recent changes: http://dejimata.com/2017/12/5/mobility-0-3-ready-for-prime-time

**Comment by shioyama** [comment]
[This is the view code](https://github.com/jmuheim/base/blob/0ef3adda2c12950298c9de5ec7df5effd4e46bb7/app/views/pages/_form.html.slim#L29-L35) you're talking about right?

**Comment by jmuheim** [comment]
Yes this is one of the views that have a form with translated fields.

**Comment by shioyama** [comment]
Ok I've confirmed this issue in your repository, and indeed adding `attribute_methods: true` to the config fixes it (but brings back the original issue you posted here). I'm debugging now, very strange...

**Comment by shioyama** [comment]
Ah, never mind, I see the issue. `translated_attribute_methods` is still in Mobility, but only on the model class, not on the instance, see [here](https://github.com/shioyama/mobility/blob/889acbe37c0cca40a3fc48945a7ccbc13d4b6c72/lib/mobility/plugins/active_record/attribute_methods.rb#L28). This should really not be extracted into the plugin.

I'll fix this and release a new patch version. Thanks for noticing the issue!

**Comment by shioyama** [comment]
@jmuheim ok issue is fixed now, try 0.3.4.

**Comment by jmuheim** [comment]
It's working, thank you so much. I love mobility gem. ❤️
